find_trending_companies:
  description: >
    Find the top trending companies in {sector} by searching the web for the latest news.
    Find new companies that you haven't found before.
  expected output: >
    A list of trending companies in {sector}
  agent: trending_company_finder
  output_file: trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending companies, you research and produce a comprehensive investment prospectus of each company.
  expected output: >
    A detailed investment prospectus for each company, in both json and markdown formats
  agent: financial_researcher
  context: >
    find_trending_companies
  output_files: >
    output/investment_prospectuses.json
    output/investment_prospectuses_summary.json
    output/investment_prospectuses.md
    output/investment_prospectuses_summary.md

pick_best_company:
  description: >
    Given a list of researched companies with investment potential, you select the best 1 for investment,
    notifying the user and then providing a detailed report. Don't pick the same company twice.
  expected output: >
    A detailed report of the best company to invest in, in markdown format
  agent: stock_picker
  context: >
    research_trending_companies
  output_file: output/best_investment.md







